### ISSUE TITLE
Breaks on ESLint v3.16.1

### ISSUE THREAD

**Issue by thealjey** [gajus/eslint-plugin-flowtype#201] opened 2017-02-24 20:39 UTC
```
TypeError: Cannot read property 'value' of null
    at node_modules/eslint-plugin-flowtype/dist/rules/typeColonSpacing/reporter.js:36:14
    at node_modules/eslint-plugin-flowtype/dist/rules/typeColonSpacing/evaluateTypical.js:32:7
    at arrayEach (node_modules/lodash/lodash.js:537:11)
    at Function.forEach (node_modules/lodash/lodash.js:9359:14)
    at EventEmitter.<anonymous> (node_modules/eslint-plugin-flowtype/dist/rules/typeColonSpacing/evaluateFunctions.js:28:22)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:189:7)
    at NodeEventGenerator.enterNode (node_modules/eslint/lib/util/node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode (node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (node_modules/eslint/lib/util/comment-event-generator.js:98:23)
```

`sourceCode.getFirstToken(node, node.optional ? 2 : 1)` returns `null` in `node_modules/eslint-plugin-flowtype/dist/rules/typeColonSpacing/evaluateTypical.js:20`

**Comment by abouthiroppy** [comment] 2017-02-24 22:16
+1

**Comment by wyze** [comment] 2017-02-27 14:58
This is a duplicate of #196 and was fixed with #197.

**Comment by gajus** [comment] 2017-02-27 15:06
Closing as duplicate.

**Closed by gajus** 2017-02-27 15:06 UTC
Labels: bug, help wanted

**Comment by capaj** [comment] 2017-03-13 12:04
I have a similar on 2.30.3:

```
